### ISSUE TITLE
Add filters feature for the redis keys section

### ISSUE THREAD

**Issue by DumasOlivier** [OpenGems/redis_web_manager#10]
Allow the user to filter his keys by type expiration date etc.

- [x] By type
- [x] By expiration
- [x] By size

**Comment by pathaknv** [comment]
@DumasOlivier If anyone has not started working on filter by size and expiration. I would like work on it. BTW how filters option will be provided for size and expiration?

**Comment by DumasOlivier** [comment]
@pathaknv that would be awesome ! 👍 
We can imagine two up and down arrows on Expiration date and filters to order them asc or desc order... Of course if you have a better idea we can do it !
Here is a screen of what I think : 
<img width="501" alt="Capture d’écran 2020-02-11 à 10 53 15" src="https://user-images.githubusercontent.com/37848777/74226564-100c6880-4cbd-11ea-9f34-bb24830c3099.png">

**Comment by DumasOlivier** [comment]
Maybe that would be nice to have a dropdown filter with range for the size (from 0 to X bytes, from X to Y bytes etc)

For the Expiration Date that would also be nice to be able to filter them with a range aswell like : expire in less than one hour / one week / one month ...

What do you think you can do ? We can develop both : the sort option (my first comment with the up and down arrows) and the dropdown range filters..

**Comment by pathaknv** [comment]
@DumasOlivier 
For the Expiration Date dropdown sounds great with predefined values.

But in case of Size (from 0 to X bytes, from X to Y bytes etc). We will need to set some limit for creating the number of filter options.

And also, the up and down arrows is kind on universal which could also better fit here.

**Comment by DumasOlivier** [comment]
> But in case of Size (from 0 to X bytes, from X to Y bytes etc). We will need to set some limit for creating the number of filter options.

I totally agree with you, do you have some recommendations on the range we should apply ? Feel free to develop this feature with the range you think are the best for main usage :) 

We can split this issue in two parts if you want, one for the sorting feature (up and down arrow) and one for the dropdown filter. Up to you and what you want to do, we are very open about how the project should evolve ;)

**Comment by BorisBresciani** [comment]
Done
