### ISSUE TITLE
undefined local variable or method `info'

### ISSUE THREAD

**Issue by davidtolsma** [OpenGems/redis_web_manager#27]
Rails 5.2
configured two redises.

undefined local variable or method `info' for #<RedisWebManager::DashboardController:

**Comment by BorisBresciani** [comment]
Impossible to reproduce the bug, do you have more information ?

**Comment by davidtolsma** [comment]
Trying to figure out what the issue is. This error is not clear to what core issue is having a problem. 

Do you have an example of a configuration with multiple redis servers on a local machine?

**Comment by BorisBresciani** [comment]
Example:


```
RedisWebManager.configure do |config|
  config.redises = {
    default: Redis.new
    production: Redis.new(url: 'XXX')
}
end
```

**Comment by yizeng** [comment]
Hello @BorisBresciani !

I'm having the same issue but don't understand the example provided.

Environment: Rails 5.2.4.2, redis_web_manager 0.3.4

Here's what I have locally
``` 
config.redises = {
    default: Redis.new(url: ENV.fetch("REDIS_URL_FOR_CACHING", "redis://localhost:6379/10")),
    sidekiq: Redis.new(url: ENV.fetch("REDIS_URL_FOR_SIDEKIQ", "redis://localhost:6379/0")),
    production: Redis.new(url: ENV["REDIS_URL_FOR_CACHING"])
}
```
Redis is up and running locally at localhost:6379, and Sidekiq (which uses Redis `redis://localhost:6379/0` works without any problems)

Maybe you could provide some guidance here?

**Comment by BorisBresciani** [comment]
Hello @yizeng 

Your configuration seems correct. 

When do you have this problem ? Maybe the last instance doesn't work (`production`) do you have a value for `REDIS_URL_FOR_CACHING` ?

**Comment by yizeng** [comment]
@BorisBresciani 

Bang on! That was the problem. Thank you!

Yes, of course, I understood `config.redises` is meant to configure multiple Redis stances running on the same server.

But the documentation confused me with `default` and `production` keys, which made me configure as different environments as if `default` means default and `production` means production environment.

Maybe the doc could say 
```
config.redises = {
    instance_1: Redis.new(db: 1),
    instance_2: Redis.new(url: 'XXX')
  }
```

**Comment by BorisBresciani** [comment]
Yes true :+1:
